version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: wallet_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5252
      POSTGRES_DB: wallet_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: wallet_backend
    restart: on-failure
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/wallet_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=5252

  pgAdmin:
    image: dpage/pgadmin4
    container_name: wallet_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: melnyk.a.yu.-io46@edu.kpi.ua
      PGADMIN_DEFAULT_PASSWORD: 5252
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: